// Generate only the character ranges used by this prototype. Re-run when copy changes.
// Original font files and OFL licenses remain in the pinned Fontsource packages.
import { readFile, writeFile, mkdir } from "node:fs/promises";

const content = (
  await Promise.all(
    [
      "src/PoliticianApp.tsx",
      "src/EditorialHome.tsx",
      "src/policy-briefs.ts",
      "src/PolicyReading.tsx",
      "src/DataConnections.tsx",
      "src/integrations.ts",
      "src/politics.ts",
      "src/politics-demo.ts",
      "src/politics-reviewed.ts",
      "public/data/assembly.json",
      "index.html",
    ].map((path) => readFile(path, "utf8")),
  )
).join("");
const points = [
  ...new Set([...content].map((character) => character.codePointAt(0))),
].sort((a, b) => a - b);
let output =
  "/* Generated by scripts/prepare-fonts.mjs. Do not edit by hand. */\n";
let count = 0;
for (const [family, weight] of [
  ["noto-sans-kr", 400],
  ["noto-sans-kr", 600],
  ["noto-serif-kr", 700],
]) {
  const css = await readFile(
    `node_modules/@fontsource/${family}/${weight}.css`,
    "utf8",
  );
  for (const block of css.match(/@font-face\s*\{[^}]+\}/g) || []) {
    const ranges = block
      .match(/unicode-range:\s*([^;]+);/)[1]
      .split(",")
      .map((value) => {
        const [start, end] = value
          .trim()
          .replace(/^U\+/i, "")
          .split("-")
          .map((value) => parseInt(value, 16));
        return [start, end ?? start];
      });
    const included = points.filter((point) =>
      ranges.some(([start, end]) => point >= start && point <= end),
    );
    if (!included.length) continue;
    const fontFile = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
    output +=
      block
        .replace(
          /src:[^;]+;/,
          `src: url('../node_modules/@fontsource/${family}/files/${fontFile}') format('woff2');`,
        )
        .replace(
          /unicode-range:[^;]+;/,
          `unicode-range: ${included.map((point) => `U+${point.toString(16)}`).join(",")};`,
        ) + "\n";
    count += 1;
  }
}
await writeFile("src/generated-fonts.css", output);
await mkdir("public/licenses", { recursive: true });
const notices = await Promise.all(
  [
    "react",
    "react-dom",
    "@phosphor-icons/react",
    "@fontsource/noto-sans-kr",
    "@fontsource/noto-serif-kr",
  ].map(
    async (name) =>
      name +
      "\n\n" +
      (await readFile("node_modules/" + name + "/LICENSE", "utf8")),
  ),
);
await writeFile(
  "public/licenses/THIRD_PARTY_LICENSES.txt",
  notices.join("\n\n--------------------\n\n"),
);
console.log(
  `Prepared ${count} font ranges (${Math.round(output.length / 1024)} KB CSS). Unlisted input characters use the system fallback.`,
);
