import type { Dataset, Headline } from "./politics";
export const demo: Dataset = {
  version: 1,
  recordedAt: "2026-09-05T12:00:00Z",
  status: "fixture",
  scope: "모든 인물·발언·법안·표결·제목은 자체 작성한 가상 시연입니다.",
  sources: [],
  people: [
    {
      id: "demo-ga",
      name: "가상 의원 가",
      party: "가상 새길당",
      region: "가상 한빛갑",
      mode: "demo",
      categories: ["housing", "tax"],
      committee: "국토교통위원회 (가상)",
    },
    {
      id: "demo-na",
      name: "가상 의원 나",
      party: "가상 이음당",
      region: "가상 한빛을",
      mode: "demo",
      categories: ["housing", "care"],
      committee: "보건복지위원회 (가상)",
    },
    {
      id: "demo-da",
      name: "가상 의원 다",
      party: "가상 새길당",
      region: "가상 들녘갑",
      mode: "demo",
      categories: ["housing", "tax"],
      committee: "기획재정위원회 (가상)",
    },
  ],
  bills: [
    {
      id: "demo-rent",
      number: "가상-101",
      title: "임차보증금 보호범위 확대안",
      category: "housing",
      proposer: "가상 의원 가 등 2인",
      stage: "위원회 심사 (가상)",
      date: "2026-08-26",
      mode: "demo",
      sponsorsTotal: 2,
      sponsorsReturned: 2,
    },
    {
      id: "demo-tax",
      number: "가상-102",
      title: "보증료 지원 재원 조정안",
      category: "tax",
      proposer: "가상 의원 다 등 2인",
      stage: "본회의 가결 (가상)",
      date: "2026-08-15",
      mode: "demo",
      vote: {
        yes: 170,
        no: 95,
        abstain: 5,
        voted: 270,
        members: 300,
        date: "2026-08-28",
        rowsTotal: 270,
        rowsReturned: 3,
      },
    },
  ],
  records: [
    {
      id: "d1",
      personId: "demo-ga",
      billId: "demo-rent",
      kind: "발언",
      date: "2026-08-12",
      title: "보호 범위 확대를 약속한 공개 발언",
      quote:
        "보증금 보호의 사각지대를 줄이고, 더 많은 임차인이 보증에 가입할 수 있게 하겠습니다.",
      detail:
        "자체 작성한 가상 간담회 발언. 가입 범위 확대라는 정책 방향을 밝힌 장면입니다.",
      mode: "demo",
    },
    {
      id: "d2",
      personId: "demo-ga",
      billId: "demo-rent",
      kind: "대표발의",
      date: "2026-08-26",
      title: "임차보증금 보호범위 확대안",
      detail:
        "가상 원안 제2조: 가입 가능한 주택 범위를 확대. 제4조: 보증료 지원 대상은 소득 기준 이하 가구로 한정.",
      mode: "demo",
    },
    {
      id: "d3",
      personId: "demo-na",
      billId: "demo-rent",
      kind: "공동발의",
      date: "2026-08-26",
      title: "임차보증금 보호범위 확대안 공동발의",
      detail:
        "가상 의원 나가 공동발의자로 참여했습니다. 이 사실만으로 향후 본회의 찬성표를 확정하지 않습니다.",
      mode: "demo",
    },
    {
      id: "d4",
      personId: "demo-ga",
      billId: "demo-tax",
      kind: "표결",
      vote: "찬성",
      date: "2026-08-28",
      title: "보증료 지원 재원 조정안 찬성",
      detail:
        "가상 제3조: 지원은 취약가구에 우선 배정. 가입 확대안과 별개인 재원 조정안의 실제 행동을 시연합니다.",
      mode: "demo",
    },
    {
      id: "d5",
      personId: "demo-na",
      billId: "demo-tax",
      kind: "표결",
      vote: "반대",
      date: "2026-08-28",
      title: "보증료 지원 재원 조정안 반대",
      detail:
        "가상 의원 나의 반대 기록. 반대 이유는 이 기록만으로 확정할 수 없습니다.",
      mode: "demo",
    },
    {
      id: "d6",
      personId: "demo-da",
      billId: "demo-tax",
      kind: "표결",
      vote: "찬성",
      date: "2026-08-28",
      title: "보증료 지원 재원 조정안 찬성",
      detail: "가상 의원 다의 찬성 기록.",
      mode: "demo",
    },
    {
      id: "d7",
      personId: "demo-ga",
      billId: "demo-rent",
      kind: "추가 설명",
      date: "2026-09-01",
      title: "가입 확대와 비용 지원을 구분한 설명",
      quote:
        "가입 대상은 넓히되, 보증료 지원은 도움이 더 필요한 가구에 집중하겠습니다.",
      detail:
        "자체 작성한 가상 추가 설명. 처음 발언을 뒤집었다고 단정하기 전에 비용 지원과 가입 범위를 구분해야 합니다.",
      mode: "demo",
    },
    {
      id: "d8",
      personId: "demo-da",
      billId: "demo-rent",
      kind: "발언",
      date: "2026-09-02",
      title: "재원 추계를 요구하며 입장 유보",
      quote: "장기 재원 추계를 확인한 뒤 결정하겠습니다.",
      detail:
        "가상 발언에서 재원 조건을 명시. 반대 표결 기록이 아니라 조건부 유보입니다.",
      mode: "demo",
    },
  ],
};
const h = (
  id: string,
  title: string,
  publisher: string,
  relation: Headline["relation"] = "report",
  action = "발의",
  date = "2026-08-26",
): Headline => ({
  id,
  title,
  publisher,
  publishedAt: date + "T10:00:00+09:00",
  personIds: ["demo-ga"],
  billId: "demo-rent",
  action,
  eventDate: date,
  relation,
  verifiedLink: true,
  mode: "demo",
});
export const demoHeadlines: Headline[] = [
  h("h1", "가상 의원 가, 보증 가입 범위 확대안 발의", "가상 매체 1"),
  h("h2", "가상 의원 가, 보증 가입 범위 확대안 발의", "가상 매체 2"),
  h("h3", "보증 가입 문턱 낮춘다… 가상 의원 가 개정안 제안", "가상 매체 3"),
  h(
    "h4",
    "[정정] 모든 가구 보증료 지원 아닌 가입 범위 확대",
    "가상 매체 2",
    "correction",
    "정정",
    "2026-08-27",
  ),
  h(
    "h5",
    "가상 의원 가 측, 보증료 전액 지원 해석에 반박",
    "가상 매체 4",
    "rebuttal",
    "반박",
    "2026-08-27",
  ),
  {
    ...h(
      "h6",
      "가상 의원 가, 지원 재원 조정안에는 찬성 표결",
      "가상 매체 1",
      "new",
      "표결",
      "2026-08-28",
    ),
    billId: "demo-tax",
  },
];
